In [ ]:
import re
import string
import nltk #Natural Language tool kit

# Download required NLTK resources (run once)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
print("Libraries loaded successfully")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

Libraries loaded successfully

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

In [ ]:
text = "I absolutely LOVE this movie!!! It's amazing, but the ending was not good. 😍 #BestMovie2026"
print("Original Text:", text)

Original Text: I absolutely LOVE this movie!!! It's amazing, but the ending was not good. 😍 #BestMovie2026

In [ ]:
#1. converting into lowercase

text_lower = text.lower()

print("\n1. Lowercase:")
print(text_lower)

1. Lowercase:
i absolutely love this movie!!! it's amazing, but the ending was not good. 😍 #bestmovie2026

In [ ]:
text_no_urls = re.sub(r'http\S+|www\S+', '', text_lower)

print("\n2. Remove URLs:")
print(text_no_urls)

2. Remove URLs:
i absolutely love this movie!!! it's amazing, but the ending was not good. 😍 #bestmovie2026

In [ ]:
text_no_mentions = re.sub(r'@\w+', '', text_no_urls)
text_no_hashtags = re.sub(r'#', '', text_no_mentions)

print("\n3. Remove Mentions and Hashtags:")
print(text_no_hashtags)

3. Remove Mentions and Hashtags:
i absolutely love this movie!!! it's amazing, but the ending was not good. 😍 bestmovie2026

In [ ]:
text_no_emojis = text_no_hashtags.encode(
    'ascii', 'ignore'
).decode('ascii')

print("\n4. Remove Emojis:")
print(text_no_emojis)

4. Remove Emojis:
i absolutely love this movie!!! it's amazing, but the ending was not good.  bestmovie2026

In [ ]:
# 6. Remove Punctuation
text_no_punctuation = text_no_emojis.translate(
    str.maketrans('', '', string.punctuation)
)

print("\n5. Remove Punctuation:")
print(text_no_punctuation)

# 7. Tokenization
tokens = word_tokenize(text_no_punctuation)

print("\n6. Tokenization:")
print(tokens)

# 8. Stopword Removal
stop_words = set(stopwords.words('english'))

# Preserve important sentiment negation words
negation_words = {'not', 'no', 'never', 'neither', 'nor'}

filtered_tokens = [
    word for word in tokens
    if word not in stop_words or word in negation_words
]

print("\n7. Stopword Removal:")
print(filtered_tokens)

# 9. Stemming


stemmer = PorterStemmer()

stemmed_words = [
    stemmer.stem(word) for word in filtered_tokens
]

print("\n8. Stemming:")
print(stemmed_words)

# 10. Lemmatization
lemmatizer = WordNetLemmatizer()

lemmatized_words = [
    lemmatizer.lemmatize(word) for word in filtered_tokens
]

print("\n9. Lemmatization:")
print(lemmatized_words)

#11. Vectorization
cleaned_text = ' '.join(lemmatized_words)

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform([cleaned_text])

print("\n10. Cleaned Text for TF-IDF:")
print(cleaned_text)

print("\nTF-IDF Feature Names:")
print(vectorizer.get_feature_names_out())

print("\nTF-IDF Numerical Vector:")
print(tfidf_matrix.toarray())

5. Remove Punctuation:
i absolutely love this movie its amazing but the ending was not good  bestmovie2026

6. Tokenization:
['i', 'absolutely', 'love', 'this', 'movie', 'its', 'amazing', 'but', 'the', 'ending', 'was', 'not', 'good', 'bestmovie2026']

7. Stopword Removal:
['absolutely', 'love', 'movie', 'amazing', 'ending', 'not', 'good', 'bestmovie2026']

8. Stemming:
['absolut', 'love', 'movi', 'amaz', 'end', 'not', 'good', 'bestmovie2026']

9. Lemmatization:
['absolutely', 'love', 'movie', 'amazing', 'ending', 'not', 'good', 'bestmovie2026']

10. Cleaned Text for TF-IDF:
absolutely love movie amazing ending not good bestmovie2026

TF-IDF Feature Names:
['absolutely' 'amazing' 'bestmovie2026' 'ending' 'good' 'love' 'movie'
 'not']

TF-IDF Numerical Vector:
[[0.35355339 0.35355339 0.35355339 0.35355339 0.35355339 0.35355339
  0.35355339 0.35355339]]

In [ ]:
new='absolutely love movie amazing ending not good bestmovie2026 good absolutely'

print(new)

absolutely love movie amazing ending not good bestmovie2026 good absolutely

In [ ]:
tfidf_matrix = vectorizer.fit_transform([new])

print("\n10. Cleaned Text for TF-IDF:")
print(new)

print("\nTF-IDF Feature Names for new text:")
print(vectorizer.get_feature_names_out())

print("\nTF-IDF Numerical Vector for new text:")
print(tfidf_matrix.toarray())

10. Cleaned Text for TF-IDF:
absolutely love movie amazing ending not good bestmovie2026 good absolutely

TF-IDF Feature Names for new text:
['absolutely' 'amazing' 'bestmovie2026' 'ending' 'good' 'love' 'movie'
 'not']

TF-IDF Numerical Vector for new text:
[[0.53452248 0.26726124 0.26726124 0.26726124 0.53452248 0.26726124
  0.26726124 0.26726124]]

#Ruled based approach

In [ ]:
import pandas as pd
data = {
    "text": [
        "I love this product, it is amazing",
        "The movie was excellent and enjoyable",
        "I hate this service, it is terrible",
        "The product is bad and disappointing",
        "The experience was wonderful and fantastic"
    ],
    "sentiment": [
        "positive",
        "positive",
        "negative",
        "negative",
        "positive"
    ]
}
df=pd.DataFrame(data)
print(df)

                                         text sentiment
0          I love this product, it is amazing  positive
1       The movie was excellent and enjoyable  positive
2         I hate this service, it is terrible  negative
3        The product is bad and disappointing  negative
4  The experience was wonderful and fantastic  positive

In [ ]:
#Creating a dictionary of positive and negative words

positive_words = {
    "love", "amazing", "excellent", "enjoyable",
    "wonderful", "fantastic", "good", "great",
    "happy", "best"
}

negative_words = {
    "hate", "terrible", "bad", "disappointing",
    "poor", "worst", "sad", "awful"
}

In [ ]:
def rule_based_sentiment(text):
    # Convert text to lowercase
    text = text.lower()

    # Extract words
    words = re.findall(r'\b\w+\b', text)
    print("Extracted words", words)
    # Count positive and negative words
    positive_count = sum(word in positive_words for word in words)
    negative_count = sum(word in negative_words for word in words)

    if positive_count>negative_count:
      return "postive"
    elif negative_count> positive_count:
      return "negative"
    else:
      return "neutral"

In [ ]:
df

                                         text sentiment
0          I love this product, it is amazing  positive
1       The movie was excellent and enjoyable  positive
2         I hate this service, it is terrible  negative
3        The product is bad and disappointing  negative
4  The experience was wonderful and fantastic  positive

In [ ]:
df['rule_based_prediction']=df["text"].apply(rule_based_sentiment)

print("Final results")
print(df)

Extracted words ['i', 'love', 'this', 'product', 'it', 'is', 'amazing']
Extracted words ['the', 'movie', 'was', 'excellent', 'and', 'enjoyable']
Extracted words ['i', 'hate', 'this', 'service', 'it', 'is', 'terrible']
Extracted words ['the', 'product', 'is', 'bad', 'and', 'disappointing']
Extracted words ['the', 'experience', 'was', 'wonderful', 'and', 'fantastic']
Final results
                                         text sentiment rule_based_prediction
0          I love this product, it is amazing  positive               postive
1       The movie was excellent and enjoyable  positive               postive
2         I hate this service, it is terrible  negative              negative
3        The product is bad and disappointing  negative              negative
4  The experience was wonderful and fantastic  positive               postive

In [ ]:
user_input = input("Enter the Review")
result=rule_based_sentiment(user_input)
print(result)

Enter the Reviewbad
Extracted words ['bad']
negative

In [ ]:
df

                                         text sentiment rule_based_prediction
0          I love this product, it is amazing  positive               postive
1       The movie was excellent and enjoyable  positive               postive
2         I hate this service, it is terrible  negative              negative
3        The product is bad and disappointing  negative              negative
4  The experience was wonderful and fantastic  positive               postive

In [ ]:
X = df["text"]
y = df["sentiment"]

vectorizer = TfidfVectorizer()

X_tfidf = vectorizer.fit_transform(X)

print("\nTF-IDF Feature Matrix Shape:")
print(X_tfidf.shape)

TF-IDF Feature Matrix Shape:
(5, 20)

In [ ]:
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=vectorizer.get_feature_names_out()
)
tfidf_df

,amazing,and,bad,disappointing,enjoyable,excellent,experience,fantastic,hate,is,it,love,movie,product,service,terrible,the,this,was,wonderful
0,0.476663,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.319227,0.384569,0.476663,0.000000,0.384569,0.000000,0.000000,0.000000,0.384569,0.000000,0.000000
1,0.000000,0.314037,0.000000,0.000000,0.468913,0.468913,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.468913,0.000000,0.000000,0.000000,0.314037,0.000000,0.378316,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.458815,0.307274,0.370169,0.000000,0.000000,0.000000,0.458815,0.458815,0.000000,0.370169,0.000000,0.000000
3,0.000000,0.335004,0.500222,0.500222,0.000000,0.000000,0.000000,0.000000,0.000000,0.335004,0.000000,0.000000,0.000000,0.403576,0.000000,0.000000,0.335004,0.000000,0.000000,0.000000
4,0.000000,0.314037,0.000000,0.000000,0.000000,0.000000,0.468913,0.468913,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.314037,0.000000,0.378316,0.468913

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
#Model Training
model.fit(X_tfidf, y)
# 8. Predict Sentiment for Dummy Dataset

ml_predictions = model.predict(X_tfidf)

df["ml_prediction"] = ml_predictions

print("\nMachine Learning Results:")
print(df[["text", "sentiment", "ml_prediction"]])

Machine Learning Results:
                                         text sentiment ml_prediction
0          I love this product, it is amazing  positive      positive
1       The movie was excellent and enjoyable  positive      positive
2         I hate this service, it is terrible  negative      positive
3        The product is bad and disappointing  negative      positive
4  The experience was wonderful and fantastic  positive      positive