In [ ]:
!pip install gensim -q #Word2vec
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 68.9 MB/s eta 0:00:00

In [ ]:
corpus = [
    "machine learning is fun",
    "machine learning is powerful",
    "deep learning drives ai",
    "natural language processing is interesting"
]

corpus #Document collection

['machine learning is fun',
 'machine learning is powerful',
 'deep learning drives ai',
 'natural language processing is interesting']

In [ ]:
#Vocabulary of the document
vocab = sorted(list(set(" ".join(corpus).split())))
print("Vocabulary:", vocab)

Vocabulary: ['ai', 'deep', 'drives', 'fun', 'interesting', 'is', 'language', 'learning', 'machine', 'natural', 'powerful', 'processing']

In [ ]:
#Bag of words
bow = CountVectorizer()
bow_matrix = bow.fit_transform(corpus)

bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=bow.get_feature_names_out()
)

bow_df

,ai,deep,drives,fun,interesting,is,language,learning,machine,natural,powerful,processing
0,0,0,0,1,0,1,0,1,1,0,0,0
1,0,0,0,0,0,1,0,1,1,0,1,0
2,1,1,1,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,1,1,0,0,1,0,1

In [ ]:
corpus2 = [
    "students learn python",
    "students learn machine learning",
    "python is easy to learn",
    "machine learning is useful",
    "students use python for projects"
]

In [ ]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(corpus)

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df

,ai,deep,drives,fun,interesting,is,language,learning,machine,natural,powerful,processing
0,0.000000,0.000000,0.000000,0.640655,0.00000,0.408922,0.00000,0.408922,0.5051,0.00000,0.000000,0.00000
1,0.000000,0.000000,0.000000,0.000000,0.00000,0.408922,0.00000,0.408922,0.5051,0.00000,0.640655,0.00000
2,0.541736,0.541736,0.541736,0.000000,0.00000,0.000000,0.00000,0.345783,0.0000,0.00000,0.000000,0.00000
3,0.000000,0.000000,0.000000,0.000000,0.47633,0.304035,0.47633,0.000000,0.0000,0.47633,0.000000,0.47633

In [ ]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(corpus2)

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df

,easy,for,is,learn,learning,machine,projects,python,students,to,use,useful
0,0.000000,0.000000,0.000000,0.577350,0.000000,0.000000,0.000000,0.577350,0.577350,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.451637,0.544081,0.544081,0.000000,0.000000,0.451637,0.000000,0.000000,0.000000
2,0.530899,0.000000,0.428326,0.355549,0.000000,0.000000,0.000000,0.355549,0.000000,0.530899,0.000000,0.000000
3,0.000000,0.000000,0.469515,0.000000,0.469515,0.469515,0.000000,0.000000,0.000000,0.000000,0.000000,0.581951
4,0.000000,0.506563,0.000000,0.000000,0.000000,0.000000,0.506563,0.339251,0.339251,0.000000,0.506563,0.000000